# Generated by Django 5.1 on 2025-02-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_alter_book_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='bookname',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='library',
            name='studentname',
            field=models.CharField(max_length=120),
        ),
    ]
