# Generated by Django 5.1 on 2025-02-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_alter_student_photo_alter_student_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.CharField(default='images/default.webp', max_length=150),
        ),
        migrations.AlterField(
            model_name='student',
            name='video',
            field=models.CharField(default='images/default.webp', max_length=150),
        ),
    ]
