# Generated by Django 5.1 on 2025-02-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_alter_student_photo_alter_student_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.FileField(default='images/default.webp', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='video',
            field=models.FileField(default='videos/default.webp', upload_to='videos/'),
        ),
    ]
