# Generated by Django 5.1 on 2025-02-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_alter_student_photo_alter_student_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.FileField(blank=True, default='static/images/default.webp', upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='video',
            field=models.FileField(blank=True, default='static/videos/default.webp', upload_to='static/videos/'),
        ),
    ]
