# Generated by Django 5.1 on 2025-02-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0011_alter_student_photo_alter_student_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='video',
            field=models.FileField(default='videos/default.webp', upload_to='images/'),
        ),
    ]
