# Generated by Django 5.1 on 2025-02-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0014_alter_student_photo_alter_student_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='video',
            field=models.FileField(upload_to='media/videos/'),
        ),
    ]
